<a href="https://colab.research.google.com/github/alphaX86/Hello_ML/blob/master/Data_seperate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
import pandas as pd
import numpy as np

In [30]:
data = pd.read_csv("/content/11.2 Sri Venkateshwara College of Engineering and Technology_202015-11-19.csv")

In [31]:
data.head()

          Name  python  mysql  ...      Mobile                    Email Rising
0    A.Dharani    82.0   20.0  ...  8056669928  dharanianbu74@gmail.com      0
1  V.JEEVITHA     82.0   20.0  ...  9655705598  vjeevitha1998@gmail.com      0
2  HEMAVATHI.R   100.0  100.0  ...  7558186924   hemaravi0499@gmail.com      0
3  Mugunthan S   100.0   47.0  ...  7094532287  mugunthans718@gmail.com      0
4  Sathammai.S   100.0    8.0  ...  6374336788  vinayagar2324@gmail.com      0

[5 rows x 9 columns]

In [32]:
pd.set_option('display.max_rows', 1000)
data_filter_1 = data[data["CodeKata Score"]>15000]
data_filter_1.head()

          Name  python  mysql  ...      Mobile                    Email Rising
0    A.Dharani    82.0   20.0  ...  8056669928  dharanianbu74@gmail.com      0
1  V.JEEVITHA     82.0   20.0  ...  9655705598  vjeevitha1998@gmail.com      0
2  HEMAVATHI.R   100.0  100.0  ...  7558186924   hemaravi0499@gmail.com      0

[3 rows x 9 columns]

In [33]:
data_filter_2 = data[data["CodeKata Score"]>10000]
data_filter_2x = data_filter_2[data_filter_2["CodeKata Score"]<15000]
data_filter_2x

          Name  python  mysql  ...      Mobile                    Email Rising
3  Mugunthan S   100.0   47.0  ...  7094532287  mugunthans718@gmail.com      0

[1 rows x 9 columns]

In [34]:
data_filter_3 = data[data["CodeKata Score"]>7000]
data_filter_3x = data_filter_3[data_filter_3["CodeKata Score"]<10000]
data_filter_3x

                   Name  python  ...                       Email  Rising
4           Sathammai.S   100.0  ...     vinayagar2324@gmail.com       0
5          NIVEESHWAR S   100.0  ...    sivanivesh2315@gmail.com       0
6         KALAIARASAN K    85.0  ...     kalai.ece.a.k@gmail.com     130
7  MOHAMED ZUBAIR AHMED    82.0  ...  mohamedzubair490@gmail.com       0

[4 rows x 9 columns]

In [35]:
data_filter_4 = data[data["CodeKata Score"]<7000]
data_filter_4

                          Name  python  ...                            Email  Rising
8                   J.SUGANTHI    27.0  ...   suguudhayacharan2014@gmail.com       0
9                 thamizhpaana    29.0  ...              tamprider@gmail.com       0
10             Iyappan Samiraj    50.0  ...       shivaiyappan2210@gmail.com       0
11                Ponniyamma.R   100.0  ...          ponniravi2499@gmail.com       0
12                   SABAPATHI   100.0  ...         sharpsabapathi@gmail.com       0
13                    RAGHAVAN   100.0  ...            ragul291997@gmail.com       0
14             Melvin Dukles.R    56.0  ...           r.m.declas24@gmail.com       0
15                    Pavithra   100.0  ...         pavithraaflora@gmail.com       0
16                 PRIYANKA .S    85.0  ...        priyaprider7372@gmail.com       0
17                 v.vithyasri   100.0  ...            vithya61198@gmail.com       0
18          Abirami Anbazhagan   100.0  ...     abiramianbazhagan2@gmail.com       0
19                S.srinivasan   100.0  ...                ssr8499@gmail.com       0
20                    s.janani   100.0  ...         sathiyajananis@gmail.com       0
21                kamalishwari    32.0  ...        sparklingkamali@gmail.com       0
22                     Yuvasri   100.0  ...             sriragu328@gmail.com       0
23                      balaji    82.0  ...          balamani45678@gmail.com       0
24                     MEERA.M   100.0  ...      meeramurugaiyan00@gmail.com       0
25                   Tpavithra   100.0  ...           tpavithra274@gmail.com       0
26               sri dharshini   100.0  ...       sridharshini0103@gmail.com       0
27                    shankari    87.5  ...       shanshan10111999@gmail.com       0
28               pooja priya.B   100.0  ...         poojapriya2206@gmail.com       0
29                     chithra   100.0  ...         chithraoctober@gmail.com       0
30                  manikandan   100.0  ...  manikandanmani9111998@gmail.com       0
31              Kaliaperumal G   100.0  ...               kp7094g3@gmail.com       0
32                  SarumathiR    16.0  ...       sarurajasundaram@gmail.com       0
33                   SOWMIYA.V    85.0  ...                aymisow@gmail.com       0
34                  tamilarasi   100.0  ...     thamizhperumal2331@gmail.com       0
35                    Barath D    74.0  ...         barathdevaraj5@gmail.com       0
36                  selvakumar   100.0  ...           greekboy6677@gmail.com       0
37                   nivedha.s   100.0  ...           nivisekar205@gmail.com       0
38                     Stephen   100.0  ...            rstephen678@gmail.com       0
39                     vignesh    85.0  ...        vikeyvignesh901@gmail.com       0
40                  HSharukhan   100.0  ...       sharukh1999yasin@gmail.com       0
41                 vijayakumar   100.0  ...    vijayakumar02071999@gmail.com       0
42                   ABIRAMI.S    82.0  ...          abisakthi2759@gmail.com       0
43                  v.gowsalya    53.0  ...          vgowsalya1998@gmail.com       0
44                     ponni.p    93.0  ...          ponnisathya13@gmail.com       0
45                  PRAVEENA K   100.0  ...         praveenajaya99@gmail.com       0
46  siva sai perumal polisetti   100.0  ...        saipolisetty999@gmail.com       0
47                 MadhumathiB    16.0  ...            madhuaridha@gmail.com       0
48                   b.akshaya    82.0  ...      akshayabaskaran30@gmail.com       0
49                    bavithra     0.0  ...          bavithara3400@gmail.com       0
50                   Deivani.S     0.0  ...       selvamlathagunal@gmail.com       0
51                   Nivetha.S     0.0  ...          rojamalar1998@gmail.com       0
52                 GUNAMATHI.S     0.0  ...            gunamathi99@gmail.com       0
53                   RANJITH.R   100.0  ...            ranjithsm23@gmail.com       0
54                    u.abarna     3.0  ...          abarna2191998@gmail.com       0
55                kaviyarasi.k    16.0  ...          kaviyarasik99@gmail.com       0
56                     pravina   100.0  ...   pravinasundaramurthy@gmail.com       0
57                     M.PRIYA    43.0  ...            mvpriya6199@gmail.com       0
58                M.Nisha@mary    11.0  ...           mr.nishamary@gmail.com       0
59                    Thivviya    82.0  ...               thiv1811@gmail.com       0
60                muvendiran.m   100.0  ...    m.muvendiran2171998@gmail.com       0
61                     Aravind   100.0  ...           bobaravind40@gmail.com       0
62                     Haasini   100.0  ...             haasini.vk@gmail.com       0
63                    E.Nalini     3.0  ...          nalini1411999@gmail.com       0
64                  k.parvathi   100.0  ...         parvathi171999@gmail.com       0
65                  jayapratha    82.0  ...             pratha2508@gmail.com       0
66              Evanasundari.K    61.0  ...             paviraj734@gmail.com       0
67                    gousalya    56.0  ...     gousalyamathivanan@gmail.com       0
68                 sivaranjini     0.0  ...            sivaran2212@gmail.com       0
69                  karthika.G   100.0  ...     krishnankarthika99@gmail.com       0
70                   vignesh B    82.0  ...            heartik1997@gmail.com       0
71                 m.keerthana    97.5  ...          keerthana4522@gmail.com       0
72                  Subhashini   100.0  ...         subhashinik998@gmail.com       0
73              rajesh kumar.r    30.0  ...        kishorerajesh29@gmail.com       0
74             J.Bhuvaneshwari   100.0  ...        bhuvana25101998@gmail.com       0
75                    santhosh    82.0  ...      kindsanthosh15798@gmail.com       0
76                        Arun    95.0  ...    shanmugavelarun1998@gmail.com       0
77                  J.JAYANTHI   100.0  ...   jayanthijayasankar99@gmail.com       0
78                vikneshwaran   100.0  ...      vikneshwaran98765@gmail.com       0
79                KarthikeyanS    45.0  ...               kk417854@gmail.com       0
80                    BARATH.P    29.0  ...         barathbaby0406@gmail.com       0
81               N.Ajith kumar    82.0  ...            ajithak2898@gmail.com       0
82                mohamed nabi     0.0  ...             msdnabi007@gmail.com       0
83              yaser ahamed.A     0.0  ...           yaserahamed3@gmail.com       0

[76 rows x 9 columns]

In [36]:
data_filter_1.to_csv("data1.csv")

In [37]:
data_filter_2x.to_csv("data2.csv")

In [38]:
data_filter_3x.to_csv("data3.csv")

In [39]:
data_filter_4.to_csv("data4.csv")